name: hebby
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11  # Match your Python version
  - pytorch
  - pytorch-cuda=12.1
  - torchvision
  - torchaudio
  - imageio
  - matplotlib
  - wandb
  - numpy
  - scipy
  - psutil
  - pip
  - pip:
      - datasets
      - wandb-osh
