# Build to PDF with latexmk; quiet + useful errors
$pdf_mode = 1;
$silent   = 1;
$interaction = 'nonstopmode';

# Engines
$pdflatex = 'pdflatex -file-line-error -synctex=1 %O %S';

# Bibtex
$bibtex = 'bibtex %O %B';

# Build BOTH versions every time
@default_files = (
    'ieee_ethereal_weights.tex',
    'ieee_ethereal_weights_appendixed.tex'
);